kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: admin-role1
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["containers"]
  resourceNames: ["customers-service-ver1"]
  verbs: ["*"]
